/* Page Swap */

$("#thot-button,#mod-button,#fag-button,#odd-button,#no-button").click(function() { 
    var divToOpen = $(this).attr("id").replace("-button","");
    $("#thot,#mod,#fag,#odd,#no").hide();
    $("#"+divToOpen).show();
});


$(document).ready(function(){
  $(".check").click(function(){
      $(".hello").slideToggle();
      $(".content").slideToggle();
  });
});

// Thot Patrol --------------------------------------------------
// Arando ------------ NOT DONE ---------------------
$('#arandoThot').click(function(){
  $('#infoThot').text('Arando')
  $('#thotTitles').text('tag, tag, tag')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: cokdikbal')
  $('#thotRank').text('Rank: S+')
  $('#thotBio').text('CockCockCockCockCockCockCockCockCockCockCockCock')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/arando.png)"});
  $('#thotEventone').text('The Christmas Banning of 2016')
  $('#thotEventtwo').text('Burning Gays War of 2016-2018')
  $('#thotEventthree').text('Rabb.it Saga 2016-2018')
  $('#thotEventfour').text('Rainbow Six Siege Period 2016-2019')
  $('#thotEventfive').text('Discord.Cock 2017')
  $('#thotEventsix').text('~rule34 paki 2017')
  $('#thotEventseven').text('The NoahG11 Timeline of 2017')
  $('#thotEventeight').text('Tsmalls Bullied out of T44 2017')
  $('#thotEventnine').text('Various Roleman Appearances 2016-2018')
  $('#thotEventten').text('Thot Patrol Alt invasion 2017-2018')
  $('#thotEventeleven').text('Arando College Squat Photo 2018')
  $('#thotEventtwelve').text('NoahDkerautist Taming of 2018')
  $('#thotEventthirteen').text('Arando UPS Arc 2018-2019')
  $('#thotEventfourteen').text('ChupaKneeGrey Period 2018-2020')
  $('#thotEventfifteen').text('Hate Women Arc of 2018-Ongoing')
  $('#thotEventsixteen').text('Cum Obama Arc 2019')
  $('#thotEventseventeen').text('Arando Hardcore Minecraft Death 2019')
  $('#thotEventeighteen').text('Demi Trail Leak of 2020')
  $('#thotEventnineteen').text('Tsmalls Chained Hearts Server Saga 2020')
  $('#thotEventtwenty').text('Cunny Infection Arc 2020-Ongoing')
  $('#thotEventtwentyone').text('Noah Amogus Incident 2021')
  $('#thotEventtwentytwo').text('Sunny defection Incident 2021')
  $('#thotEventtwentythree').text('Cunny.Store Grand Opening 2021')
  $('#thotEventtwentyfour').text('Zwei Sunny Information Leak of 2021')
  $('#thotEventtwentyfive').text('CS:GO Arc 2021')
})

// Brando
$('#brandoThot').click(function(){
  $('#infoThot').text('Brando')
  $('#thotTitles').text('Whistleblower, Chaotic Neutral, Connoisseur')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: Whistleblowing, Information Gathering, Shit Stirring')
  $('#thotRank').text('Rank: S+++')
  $('#thotBio').text('Brando is a current IRA member who uses their vast network and alliances with other anti-government organizations to gather information. He first came into notoriety during the Great Christmas Banning of 2016, where he made use of a weaponized PNG to suicide-bomb the shitpost channel in Track44. For the following two years, he organized and executed insurgent invasions of Track44 with the use of fake accounts and the same weaponized PNG, known as "burning_gays.png". During this same time period, he also coordinated a devastating attack against the Tranny Army, a subgroup of Track44. In this attack, he targeted a specific member of their Army who had recently suffered the loss of their pet dog with a psychological attack by posting and immense amount of dead dog images in the chat. During this same time, he also executed a psychological operation on TSmalls, wherein he was bullied for knocking a child out at a Starbucks because he didnt like anime. This led to TSmalls going AWOL, and he has not been seen or heard from since. The next notable events he was involved in were the Sunny Whistleblowing incidents of 2020 & 2021. During these incidents, it was revealed the Sunny was dressing up in cow outfits and getting pegged by a vtuber. Following this, in 2021, it was revealed by an unknown benefactor that he was also involved in sexual acts such as getting pissed on; the fallout from this revelation would lead to another psychological attack by Brando that would case Sunny to retreat from the Cunny Zone. A notable figure throughout Brandos story is his father, known only as "Beamish" and "Beamo". He is a suspected drug dealer working within the Irish government to further the goals of the IRA; however, very little is known about him.')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/brando.png)"});
  $('#thotEventone').text('The Christmas Banning of 2016')
  $('#thotEventtwo').text('Thot Patrol Alt invasion 2017-2018')
  $('#thotEventthree').text('Dead Dog DM Incident 2017')
  $('#thotEventfour').text('Tsmalls Bullied out of T44 2017')
  $('#thotEventfive').text('VRChat Incidents of 2017-2018')
  $('#thotEventsix').text('Sunny Cow Whistleblowing Incident 2020')
  $('#thotEventseven').text('Sunny defection Incident 2021')
  $('#thotEventeight').text('Cunny Infection Arc 2020-Ongoing')
  $('#thotEventnine').text('Thailand Brandon Saga ???-2019')
  $('#thotEventten').text('Beamish Period of 2017-2018')
  $('#thotEventeleven').text('VRChat Incidents of 2017-2018')
  $('#thotEventtwelve').text('The Great Terraria Reunion of 2020')
  $('#thotEventthirteen').text('Rabb.it Saga 2016-2018')
  $('#thotEventfourteen').text('Rainbow Six Siege Period 2016-2019')
  $('#thotEventfifteen').text('Cum Obama Arc 2019')
  $('#thotEventsixteen').text('NoahDkerautist Taming of 2018')
  $('#thotEventseventeen').text('CS:GO Arc 2021')
  $('#thotEventeighteen').text('~rule34 paki 2017')
  $('#thotEventnineteen').text('Sunny defection Incident 2021')
  $('#thotEventtwenty').text('')
  $('#thotEventtwentyone').text('')
  $('#thotEventtwentytwo').text('')
  $('#thotEventtwentythree').text('')
  $('#thotEventtwentyfour').text('')
  $('#thotEventtwentyfive').text('')
})

// zwei ------------ NOT DONE ---------------------
$('#zweiThot').click(function(){
  $('#infoThot').text('zwei')
  $('#thotTitles').text('Whistleblower, Chaotic Neutral, Connoisseur')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: Whistleblowing, Information Gathering, Shit Stirring')
  $('#thotRank').text('Rank: S+++')
  $('#thotBio').text('Brando is a current IRA member who uses their vast network and alliances with other anti-government organizations to gather information. He first came into notoriety during the Great Christmas Banning of 2016, where he made use of a weaponized PNG to suicide-bomb the shitpost channel in Track44. For the following two years, he organized and executed insurgent invasions of Track44 with the use of fake accounts and the same weaponized PNG, known as "burning_gays.png". During this same time period, he also coordinated a devastating attack against the Tranny Army, a subgroup of Track44. In this attack, he targeted a specific member of their Army who had recently suffered the loss of their pet dog with a psychological attack by posting and immense amount of dead dog images in the chat. During this same time, he also executed a psychological operation on TSmalls, wherein he was bullied for knocking a child out at a Starbucks because he didnt like anime. This led to TSmalls going AWOL, and he has not been seen or heard from since. The next notable events he was involved in were the Sunny Whistleblowing incidents of 2020 & 2021. During these incidents, it was revealed the Sunny was dressing up in cow outfits and getting pegged by a vtuber. Following this, in 2021, it was revealed by an unknown benefactor that he was also involved in sexual acts such as getting pissed on; the fallout from this revelation would lead to another psychological attack by Brando that would case Sunny to retreat from the Cunny Zone. A notable figure throughout Brandos story is his father, known only as "Beamish" and "Beamo". He is a suspected drug dealer working within the Irish government to further the goals of the IRA; however, very little is known about him.')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/zwei.png)"});
  $('#thotEventone').text('')
  $('#thotEventtwo').text('')
  $('#thotEventthree').text('')
  $('#thotEventfour').text('')
  $('#thotEventfive').text('')
  $('#thotEventsix').text('')
  $('#thotEventseven').text('')
  $('#thotEventeight').text('')
  $('#thotEventnine').text('')
  $('#thotEventten').text('')
  $('#thotEventeleven').text('')
  $('#thotEventtwelve').text('')
  $('#thotEventthirteen').text('')
  $('#thotEventfourteen').text('')
  $('#thotEventfifteen').text('')
  $('#thotEventsixteen').text('')
  $('#thotEventseventeen').text('')
  $('#thotEventeighteen').text('')
  $('#thotEventnineteen').text('')
  $('#thotEventtwenty').text('')
  $('#thotEventtwentyone').text('')
  $('#thotEventtwentytwo').text('')
  $('#thotEventtwentythree').text('')
  $('#thotEventtwentyfour').text('')
  $('#thotEventtwentyfive').text('')
})

// sumi ------------ NOT DONE ---------------------
$('#sumiThot').click(function(){
  $('#infoThot').text('sumi')
  $('#thotTitles').text('Whistleblower, Chaotic Neutral, Connoisseur')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: Whistleblowing, Information Gathering, Shit Stirring')
  $('#thotRank').text('Rank: S+++')
  $('#thotBio').text('Brando is a current IRA member who uses their vast network and alliances with other anti-government organizations to gather information. He first came into notoriety during the Great Christmas Banning of 2016, where he made use of a weaponized PNG to suicide-bomb the shitpost channel in Track44. For the following two years, he organized and executed insurgent invasions of Track44 with the use of fake accounts and the same weaponized PNG, known as "burning_gays.png". During this same time period, he also coordinated a devastating attack against the Tranny Army, a subgroup of Track44. In this attack, he targeted a specific member of their Army who had recently suffered the loss of their pet dog with a psychological attack by posting and immense amount of dead dog images in the chat. During this same time, he also executed a psychological operation on TSmalls, wherein he was bullied for knocking a child out at a Starbucks because he didnt like anime. This led to TSmalls going AWOL, and he has not been seen or heard from since. The next notable events he was involved in were the Sunny Whistleblowing incidents of 2020 & 2021. During these incidents, it was revealed the Sunny was dressing up in cow outfits and getting pegged by a vtuber. Following this, in 2021, it was revealed by an unknown benefactor that he was also involved in sexual acts such as getting pissed on; the fallout from this revelation would lead to another psychological attack by Brando that would case Sunny to retreat from the Cunny Zone. A notable figure throughout Brandos story is his father, known only as "Beamish" and "Beamo". He is a suspected drug dealer working within the Irish government to further the goals of the IRA; however, very little is known about him.')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/sumi.png)"});
  $('#thotEventone').text('')
  $('#thotEventtwo').text('')
  $('#thotEventthree').text('')
  $('#thotEventfour').text('')
  $('#thotEventfive').text('')
  $('#thotEventsix').text('')
  $('#thotEventseven').text('')
  $('#thotEventeight').text('')
  $('#thotEventnine').text('')
  $('#thotEventten').text('')
  $('#thotEventeleven').text('')
  $('#thotEventtwelve').text('')
  $('#thotEventthirteen').text('')
  $('#thotEventfourteen').text('')
  $('#thotEventfifteen').text('')
  $('#thotEventsixteen').text('')
  $('#thotEventseventeen').text('')
  $('#thotEventeighteen').text('')
  $('#thotEventnineteen').text('')
  $('#thotEventtwenty').text('')
  $('#thotEventtwentyone').text('')
  $('#thotEventtwentytwo').text('')
  $('#thotEventtwentythree').text('')
  $('#thotEventtwentyfour').text('')
  $('#thotEventtwentyfive').text('')
})

// ikea ------------ NOT DONE ---------------------
$('#ikeaThot').click(function(){
  $('#infoThot').text('ikea')
  $('#thotTitles').text('Whistleblower, Chaotic Neutral, Connoisseur')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: Whistleblowing, Information Gathering, Shit Stirring')
  $('#thotRank').text('Rank: S+++')
  $('#thotBio').text('Brando is a current IRA member who uses their vast network and alliances with other anti-government organizations to gather information. He first came into notoriety during the Great Christmas Banning of 2016, where he made use of a weaponized PNG to suicide-bomb the shitpost channel in Track44. For the following two years, he organized and executed insurgent invasions of Track44 with the use of fake accounts and the same weaponized PNG, known as "burning_gays.png". During this same time period, he also coordinated a devastating attack against the Tranny Army, a subgroup of Track44. In this attack, he targeted a specific member of their Army who had recently suffered the loss of their pet dog with a psychological attack by posting and immense amount of dead dog images in the chat. During this same time, he also executed a psychological operation on TSmalls, wherein he was bullied for knocking a child out at a Starbucks because he didnt like anime. This led to TSmalls going AWOL, and he has not been seen or heard from since. The next notable events he was involved in were the Sunny Whistleblowing incidents of 2020 & 2021. During these incidents, it was revealed the Sunny was dressing up in cow outfits and getting pegged by a vtuber. Following this, in 2021, it was revealed by an unknown benefactor that he was also involved in sexual acts such as getting pissed on; the fallout from this revelation would lead to another psychological attack by Brando that would case Sunny to retreat from the Cunny Zone. A notable figure throughout Brandos story is his father, known only as "Beamish" and "Beamo". He is a suspected drug dealer working within the Irish government to further the goals of the IRA; however, very little is known about him.')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/ikea.png)"});
  $('#thotEventone').text('')
  $('#thotEventtwo').text('')
  $('#thotEventthree').text('')
  $('#thotEventfour').text('')
  $('#thotEventfive').text('')
  $('#thotEventsix').text('')
  $('#thotEventseven').text('')
  $('#thotEventeight').text('')
  $('#thotEventnine').text('')
  $('#thotEventten').text('')
  $('#thotEventeleven').text('')
  $('#thotEventtwelve').text('')
  $('#thotEventthirteen').text('')
  $('#thotEventfourteen').text('')
  $('#thotEventfifteen').text('')
  $('#thotEventsixteen').text('')
  $('#thotEventseventeen').text('')
  $('#thotEventeighteen').text('')
  $('#thotEventnineteen').text('')
  $('#thotEventtwenty').text('')
  $('#thotEventtwentyone').text('')
  $('#thotEventtwentytwo').text('')
  $('#thotEventtwentythree').text('')
  $('#thotEventtwentyfour').text('')
  $('#thotEventtwentyfive').text('')
})

// jamie ------------ NOT DONE ---------------------
$('#jamieThot').click(function(){
  $('#infoThot').text('Major')
  $('#thotTitles').text('Whistleblower, Chaotic Neutral, Connoisseur')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: Whistleblowing, Information Gathering, Shit Stirring')
  $('#thotRank').text('Rank: S+++')
  $('#thotBio').text('Brando is a current IRA member who uses their vast network and alliances with other anti-government organizations to gather information. He first came into notoriety during the Great Christmas Banning of 2016, where he made use of a weaponized PNG to suicide-bomb the shitpost channel in Track44. For the following two years, he organized and executed insurgent invasions of Track44 with the use of fake accounts and the same weaponized PNG, known as "burning_gays.png". During this same time period, he also coordinated a devastating attack against the Tranny Army, a subgroup of Track44. In this attack, he targeted a specific member of their Army who had recently suffered the loss of their pet dog with a psychological attack by posting and immense amount of dead dog images in the chat. During this same time, he also executed a psychological operation on TSmalls, wherein he was bullied for knocking a child out at a Starbucks because he didnt like anime. This led to TSmalls going AWOL, and he has not been seen or heard from since. The next notable events he was involved in were the Sunny Whistleblowing incidents of 2020 & 2021. During these incidents, it was revealed the Sunny was dressing up in cow outfits and getting pegged by a vtuber. Following this, in 2021, it was revealed by an unknown benefactor that he was also involved in sexual acts such as getting pissed on; the fallout from this revelation would lead to another psychological attack by Brando that would case Sunny to retreat from the Cunny Zone. A notable figure throughout Brandos story is his father, known only as "Beamish" and "Beamo". He is a suspected drug dealer working within the Irish government to further the goals of the IRA; however, very little is known about him.')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/major.png)"});
  $('#thotEventone').text('')
  $('#thotEventtwo').text('')
  $('#thotEventthree').text('')
  $('#thotEventfour').text('')
  $('#thotEventfive').text('')
  $('#thotEventsix').text('')
  $('#thotEventseven').text('')
  $('#thotEventeight').text('')
  $('#thotEventnine').text('')
  $('#thotEventten').text('')
  $('#thotEventeleven').text('')
  $('#thotEventtwelve').text('')
  $('#thotEventthirteen').text('')
  $('#thotEventfourteen').text('')
  $('#thotEventfifteen').text('')
  $('#thotEventsixteen').text('')
  $('#thotEventseventeen').text('')
  $('#thotEventeighteen').text('')
  $('#thotEventnineteen').text('')
  $('#thotEventtwenty').text('')
  $('#thotEventtwentyone').text('')
  $('#thotEventtwentytwo').text('')
  $('#thotEventtwentythree').text('')
  $('#thotEventtwentyfour').text('')
  $('#thotEventtwentyfive').text('')
})

// Tipper ------------ NOT DONE ---------------------
$('#tipperThot').click(function(){
  $('#infoThot').text('Tipper')
  $('#thotTitles').text('Whistleblower, Chaotic Neutral, Connoisseur')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: Whistleblowing, Information Gathering, Shit Stirring')
  $('#thotRank').text('Rank: S+++')
  $('#thotBio').text('Brando is a current IRA member who uses their vast network and alliances with other anti-government organizations to gather information. He first came into notoriety during the Great Christmas Banning of 2016, where he made use of a weaponized PNG to suicide-bomb the shitpost channel in Track44. For the following two years, he organized and executed insurgent invasions of Track44 with the use of fake accounts and the same weaponized PNG, known as "burning_gays.png". During this same time period, he also coordinated a devastating attack against the Tranny Army, a subgroup of Track44. In this attack, he targeted a specific member of their Army who had recently suffered the loss of their pet dog with a psychological attack by posting and immense amount of dead dog images in the chat. During this same time, he also executed a psychological operation on TSmalls, wherein he was bullied for knocking a child out at a Starbucks because he didnt like anime. This led to TSmalls going AWOL, and he has not been seen or heard from since. The next notable events he was involved in were the Sunny Whistleblowing incidents of 2020 & 2021. During these incidents, it was revealed the Sunny was dressing up in cow outfits and getting pegged by a vtuber. Following this, in 2021, it was revealed by an unknown benefactor that he was also involved in sexual acts such as getting pissed on; the fallout from this revelation would lead to another psychological attack by Brando that would case Sunny to retreat from the Cunny Zone. A notable figure throughout Brandos story is his father, known only as "Beamish" and "Beamo". He is a suspected drug dealer working within the Irish government to further the goals of the IRA; however, very little is known about him.')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/tipper.png)"});
  $('#thotEventone').text('')
  $('#thotEventtwo').text('')
  $('#thotEventthree').text('')
  $('#thotEventfour').text('')
  $('#thotEventfive').text('')
  $('#thotEventsix').text('')
  $('#thotEventseven').text('')
  $('#thotEventeight').text('')
  $('#thotEventnine').text('')
  $('#thotEventten').text('')
  $('#thotEventeleven').text('')
  $('#thotEventtwelve').text('')
  $('#thotEventthirteen').text('')
  $('#thotEventfourteen').text('')
  $('#thotEventfifteen').text('')
  $('#thotEventsixteen').text('')
  $('#thotEventseventeen').text('')
  $('#thotEventeighteen').text('')
  $('#thotEventnineteen').text('')
  $('#thotEventtwenty').text('')
  $('#thotEventtwentyone').text('')
  $('#thotEventtwentytwo').text('')
  $('#thotEventtwentythree').text('')
  $('#thotEventtwentyfour').text('')
  $('#thotEventtwentyfive').text('')
})

// noah ------------ NOT DONE ---------------------
$('#noahThot').click(function(){
  $('#infoThot').text('Noah')
  $('#thotTitles').text('Whistleblower, Chaotic Neutral, Connoisseur')
  $('#thotGroup').text('Group: Thot Patrol')
  $('#thotSkills').text('Skills: Whistleblowing, Information Gathering, Shit Stirring')
  $('#thotRank').text('Rank: S+++')
  $('#thotBio').text('Brando is a current IRA member who uses their vast network and alliances with other anti-government organizations to gather information. He first came into notoriety during the Great Christmas Banning of 2016, where he made use of a weaponized PNG to suicide-bomb the shitpost channel in Track44. For the following two years, he organized and executed insurgent invasions of Track44 with the use of fake accounts and the same weaponized PNG, known as "burning_gays.png". During this same time period, he also coordinated a devastating attack against the Tranny Army, a subgroup of Track44. In this attack, he targeted a specific member of their Army who had recently suffered the loss of their pet dog with a psychological attack by posting and immense amount of dead dog images in the chat. During this same time, he also executed a psychological operation on TSmalls, wherein he was bullied for knocking a child out at a Starbucks because he didnt like anime. This led to TSmalls going AWOL, and he has not been seen or heard from since. The next notable events he was involved in were the Sunny Whistleblowing incidents of 2020 & 2021. During these incidents, it was revealed the Sunny was dressing up in cow outfits and getting pegged by a vtuber. Following this, in 2021, it was revealed by an unknown benefactor that he was also involved in sexual acts such as getting pissed on; the fallout from this revelation would lead to another psychological attack by Brando that would case Sunny to retreat from the Cunny Zone. A notable figure throughout Brandos story is his father, known only as "Beamish" and "Beamo". He is a suspected drug dealer working within the Irish government to further the goals of the IRA; however, very little is known about him.')
  $("#avatarThot").css({"background-image": "url(./img/pfp/thots/noah.png)"});
  $('#thotEventone').text('')
  $('#thotEventtwo').text('')
  $('#thotEventthree').text('')
  $('#thotEventfour').text('')
  $('#thotEventfive').text('')
  $('#thotEventsix').text('')
  $('#thotEventseven').text('')
  $('#thotEventeight').text('')
  $('#thotEventnine').text('')
  $('#thotEventten').text('')
  $('#thotEventeleven').text('')
  $('#thotEventtwelve').text('')
  $('#thotEventthirteen').text('')
  $('#thotEventfourteen').text('')
  $('#thotEventfifteen').text('')
  $('#thotEventsixteen').text('')
  $('#thotEventseventeen').text('')
  $('#thotEventeighteen').text('')
  $('#thotEventnineteen').text('')
  $('#thotEventtwenty').text('')
  $('#thotEventtwentyone').text('')
  $('#thotEventtwentytwo').text('')
  $('#thotEventtwentythree').text('')
  $('#thotEventtwentyfour').text('')
  $('#thotEventtwentyfive').text('')
})